MovieStore.MVC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieStore.Core.Models.Request;
using MovieStore.Core.ServiceInterfaces;
using MovieStore.Core.Entities;
using MovieStore.Core.RepositoryInterfaces;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;

namespace MovieStore.MVC.Controllers
{
    // 1.  Purchase a Movie, HttpPost, store that info in the Purchase table
    // http:localhost:12112/User/Purchase -- HttpPost
    //purchase action result
    // first check whether the user already bought that movie
    // BUY Buuton in the Movie Details Page will call the above method
    // if user already bought that movie, then replace Buy button with Watch Movie button
    // 2. Get all the Movies Purchased by user, loged in User, take userid from HttpContext and get all the movies
    // and give them to Movie Card partial view
    // http:localhost:12112/User/Purchases -- HttpGet
    // 3. Create a Review for a Movie for Loged In user , take userid from HttpContext and save info in Review Table
    // http:localhost:12112/User/review -- HttpPost
    // Review Button will open a popup and ask user to enter a small review in textarea and have him enter
    // movie rating between 1 and 10 and then save
    // 4. Get all the Reviews done my loged in User,
    // http:localhost:12112/User/reviews -- HttpGet
    // 5. Add a Favorite Movie for Loged In User
    // http:localhost:12112/User/Favorite -- HttpPost
    // add another button called favorite, same conecpt as Purchase
    // FontAweomse libbary and use buttons from there
    // 6.Check if a particular Movie has been added as Favorite by logedin user
    // http:localhost:12112/User/movie/{12}/favorite  HttpGet
    // 7. Remove favorite
    // http:localhost:12112/User/Favorite -- Httpdelete
    [Authorize]
    public class UserController : Controller
    { 
        
        private readonly IUserService _userService;
        
        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        [HttpGet] //加载
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Purchase(PurchaseRequestModel purchaseRequestModel)
        {
            purchaseRequestModel.UserId = Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);

            await _userService.Purchase(purchaseRequestModel);
            //using (var httpClient=new HttpClient())
            //{
            //    var JsonContent = new StringContent(JsonConvert.SerializeObject(purchaseRequestModel), Encoding.UTF8, "application/json");
            //    await httpClient.PostAsync("http://localhost:50404/api/Purchase", JsonContent);
            //}
     
            return LocalRedirect("~/");
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Purchases()
        {
            var userId = Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);
            var movies = await _userService.PurchasedMovies(userId);
            return View(movies);
        }
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Review(Review review)
        {
            review.UserId = Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);
            
            await _userService.SaveReview(review);

            return LocalRedirect("~/");
        }

       [HttpGet]
        public async Task<ActionResult> Reviews()
        {
            var userId = Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);
            var reviews = await _userService.ReviewListbyUser(userId);
           

            return View(reviews);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Favorite(FavoriteRequestModel favoriteRequestModel)
        {
            favoriteRequestModel.UserId = Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);

            await _userService.Favorite(favoriteRequestModel);

            return RedirectToAction("Details", "Movies", new { movieId=favoriteRequestModel.MovieId});
        }
      
        [HttpGet]
        [Route("/User/Movie/{movieId}/Favorite")]
        public async Task<JsonResult> CheckFavorite([FromRoute]int movieId)
        {
            var userId = Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);
            bool isFavorited =  await _userService.IsFavorited(userId, movieId);
            return Json(isFavorited);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteFavorite(FavoriteRequestModel favoriteRequestModel)
        {
            var userId = Convert.ToInt32(HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);
            favoriteRequestModel.UserId = userId;
            await _userService.RemoveFavorite(favoriteRequestModel);
            return RedirectToAction("Details", "Movies", new { movieId = favoriteRequestModel.MovieId });
        }

        //Filters in ASP.NET
        //Some piece of code that runs either before a controller or action method executes or when some event happens
        //that runs before or after specific stages in the http pipeline
        //1.Authorization
        //2.Action Filter 
        //3.Result Filter
        //4.Exception filter, but in real world we used Exception middleware to cach exception
        //5.Resource filter
    }
}

MovieStore.MVC/Views/Shared/Components/Genres/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieStore.Core.ServiceInterfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieStore.MVC.Views.Shared.Components.Genres
{
    public class GenresViewComponent:ViewComponent
    {
        private readonly IGenreService _genreService;
        public GenresViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            return View(genres);
        }
    }

}

MovieStore.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieStore.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="https://kit.fontawesome.com/be63d18a46.js" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieStore.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Top Movies</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown">Genres</a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                @await Component.InvokeAsync("Genres")
                            </div>
                        </li>
                        @if (Context.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Purchases">Purchased</a>
                            </li>
                            <li class="nav-item">
                               <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Reviews">Reviews</a>
                            </li>
                        }
                        <partial name="_LogResult" />
                    </ul>
                    @*
                        the same menu on every page
                    *@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody() @*look for specific pages *@
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MovieStore.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MovieStore.MVC/Views/Shared/_LogResult.cshtml
@* check if the User is Authenticated and if Yes, then show his First Name and Last Name
    else show Login and SinUp buttons*@
@if (User.Identity.IsAuthenticated)
{
    <li ngbDropdown class="nav-item dropdown text-capitalize">
        <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown"
           style="cursor: pointer;" aria-haspopup="true"
           aria-expanded="false">
            @User.Claims.FirstOrDefault(c => c.Type == System.Security.Claims.ClaimTypes.GivenName).Value
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item">Library (myMoviesCount)</a>
            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Log Out</a>
            <a class="dropdown-item">My Account</a>
        </div>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Signup</a>
    </li>
}

MovieStore.MVC/Views/Shared/_MovieCard.cshtml
@model MovieStore.Core.Entities.Movie

    <div class="col-6 cl-lg-3 col-sm-4 col-xl-2">
        <a href="@Url.Action("Details", "Movies", new {movieId=Model.Id })"> @*helpful for just getting the url portion*@          
            <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
            @*//@Model meaning the one at the top*@
        </a>

    </div>

MovieStore.MVC/Views/Shared/_Review.cshtml
@model MovieStore.Core.Entities.Movie

<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Review</h4>
        <button type="button" class="closemodal">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <form asp-action="Review" asp-controller="User" method="post">
            <input name="MovieId" type="hidden" value="@Model.Id" />
            <div class="row">
                <div class="col-sm-2">
                    Comment:
                </div>
                <div class="col-sm-10">
                    <textarea name="ReviewText" rows="4" cols="50" ></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    1/10 Rating (1 is bad, 10 is good):
                </div>
                <div class="col-sm-10">
                    <select id="example-1to10" name="Rating" autocomplete="off" value="@Model.Rating">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <button type="submit" class="btn btn-primary closemodal" >Save</button>
                </div>
                <div class="col-sm-10">
                    <button type="button" class="btn btn-primary closemodal" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>
    </div>
</div>